In [3]:
import numpy as np

np.set_printoptions(precision=4, suppress=True)

In [7]:
T = np.load('/mnt/D494C4CF94C4B4F0/Trampoline_avril2025/Calib_trampo_avril2025/results_calib/calib_0429/WorldTCam_opt.npz')['arr_0']

#print(T)
T12 = np.linalg.inv(T[0]) @ T[2]
T21 = np.linalg.inv(T[2]) @ T[0]

print(T12)
print(np.linalg.inv(T12))
print(T21)


# FORMULA: 1T2 = inv(T1) @ T2

[[    0.9386    -0.1866     0.2902 -1460.2304]
 [   -0.0991     0.6598     0.7448 -6434.0746]
 [   -0.3305    -0.7279     0.6008   600.2863]
 [    0.         0.         0.         1.    ]]
[[   0.9386   -0.0991   -0.3305  931.5866]
 [  -0.1866    0.6598   -0.7279 4409.8595]
 [   0.2902    0.7448    0.6008 4855.4318]
 [   0.        0.        0.        1.    ]]
[[   0.9386   -0.0991   -0.3305  931.5866]
 [  -0.1866    0.6598   -0.7279 4409.8595]
 [   0.2902    0.7448    0.6008 4855.4318]
 [   0.        0.        0.        1.    ]]
